=== satish-raja/RestAssuredFramework/src/test/resources/schemas/post/update_post_response_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "PostResponse",
  "type": "object",
  "required": ["id", "user_id", "title", "body"],
  "properties": {
    "id": {
      "type": "integer"
    },
    "user_id": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "body": {
      "type": "string"
    }
  }
}

=== satish-raja/RestAssuredFramework/data/attachments/aa7db8ed6de0cb0236ab68f11dfdbd64.json
[
    {
        "id": 219497,
        "user_id": 7993636,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219486,
        "user_id": 7993563,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219476,
        "user_id": 7993463,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219463,
        "user_id": 7993443,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219461,
        "user_id": 7993439,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219344,
        "user_id": 7992747,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219335,
        "user_id": 7992731,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219326,
        "user_id": 7992710,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219316,
        "user_id": 7992695,
        "title": "Get Post Title",
        "body": "Get post body text"
    },
    {
        "id": 219308,
        "user_id": 7992660,
        "title": "Get Post Title",
        "body": "Get post body text"
    }
]
